const c=document.getElementById('game'),x=c.getContext('2d'),W=c.width,H=c.height,$=i=>document.getElementById(i);
let balance=+localStorage.getItem('bd2_balance')||1000,xp=+localStorage.getItem('bd2_xp')||0,wins=+localStorage.getItem('bd2_wins')||0,losses=+localStorage.getItem('bd2_losses')||0,streak=+localStorage.getItem('bd2_streak')||0,best=+localStorage.getItem('bd2_best')||0,bet=25,diff='medium',ps=0,as=0,turn='player',active=false,moving=false,drag=false,start=null,now=null,sound=true,balls=[];
const pockets=[[30,30],[W/2,24],[W-30,30],[30,H-30],[W/2,H-24],[W-30,H-30]];
function tone(f=440,d=.06){if(!sound)return;let A=window.AudioContext||window.webkitAudioContext;if(!A)return;let a=new A,o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.04;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}
function rank(){return xp>=3000?'Master':xp>=1500?'Diamond':xp>=700?'Gold':xp>=250?'Silver':'Bronze'}
function save(){[['bd2_balance',balance],['bd2_xp',xp],['bd2_wins',wins],['bd2_losses',losses],['bd2_streak',streak],['bd2_best',best]].forEach(v=>localStorage.setItem(v[0],v[1]))}
function ui(){$('balance').textContent=Math.floor(balance);$('playerScore').textContent=ps;$('aiScore').textContent=as;$('turn').textContent=turn==='player'?'أنت':'النظام';$('wins').textContent=wins;$('losses').textContent=losses;$('streak').textContent=streak;$('bestStreak').textContent=best;$('rank').textContent=rank();$('xpText').textContent=xp+' XP'}
function B(px,py,r,col,id,q=false){return{x:px,y:py,vx:0,vy:0,r,col,id,q,p:false}}
function rack(){balls=[B(240,H/2,17,'#fff','cue',true)];let cs=['#ffd43b','#4dabf7','#ff6b6b','#a855f7','#ff922b','#20c997','#f06595'],id=1;for(let r=0;r<4;r++)for(let j=0;j<=r&&id<=7;j++,id++)balls.push(B(760+r*32,H/2-r*18+j*36,16,cs[id-1],id))}
document.querySelectorAll('[data-bet]').forEach(b=>b.onclick=()=>{if(active)return;bet=+b.dataset.bet;document.querySelectorAll('[data-bet]').forEach(v=>v.classList.remove('active'));b.classList.add('active')});
document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{if(active)return;diff=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(v=>v.classList.remove('active'));b.classList.add('active')});
$('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').textContent=sound?'🔊':'🔇'};
$('newGame').onclick=()=>{if(active||moving)return;if(balance<bet){$('message').textContent='الرصيد الافتراضي غير كافٍ.';return}balance-=bet;ps=as=0;turn='player';active=true;rack();save();ui();$('message').textContent='دورك: اسحب من الكرة البيضاء.';tone(520)};
function draw(){x.clearRect(0,0,W,H);let g=x.createRadialGradient(W/2,H/2,40,W/2,H/2,700);g.addColorStop(0,'#0f875b');g.addColorStop(1,'#07583c');x.fillStyle=g;x.fillRect(0,0,W,H);x.strokeStyle='#d1a45f';x.lineWidth=8;x.strokeRect(13,13,W-26,H-26);pockets.forEach(p=>{x.beginPath();x.arc(p[0],p[1],27,0,7);x.fillStyle='#050e11';x.fill()});balls.forEach(b=>{if(b.p)return;x.beginPath();x.arc(b.x,b.y,b.r,0,7);x.fillStyle=b.col;x.fill();if(!b.q){x.beginPath();x.arc(b.x,b.y,7,0,7);x.fillStyle='#fff';x.fill();x.fillStyle='#111';x.font='9px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(b.id,b.x,b.y)}});if(drag&&start&&now){let q=balls.find(b=>b.q&&!b.p),dx=q.x-now.x,dy=q.y-now.y,l=Math.hypot(dx,dy)||1,nx=dx/l,ny=dy/l;x.setLineDash([10,8]);x.beginPath();x.moveTo(q.x,q.y);x.lineTo(q.x+nx*500,q.y+ny*500);x.strokeStyle='#ffffffaa';x.lineWidth=3;x.stroke();x.setLineDash([]);$('powerFill').style.width=Math.min(140,l*.7)+'px'}else $('powerFill').style.width='0'}
function physics(){let mv=false;balls.forEach(b=>{if(b.p)return;b.x+=b.vx;b.y+=b.vy;b.vx*=.988;b.vy*=.988;if(Math.abs(b.vx)<.02)b.vx=0;if(Math.abs(b.vy)<.02)b.vy=0;if(b.x-b.r<30){b.x=30+b.r;b.vx=Math.abs(b.vx)}if(b.x+b.r>W-30){b.x=W-30-b.r;b.vx=-Math.abs(b.vx)}if(b.y-b.r<30){b.y=30+b.r;b.vy=Math.abs(b.vy)}if(b.y+b.r>H-30){b.y=H-30-b.r;b.vy=-Math.abs(b.vy)}if(Math.hypot(b.vx,b.vy)>.05)mv=true});for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){let a=balls[i],b=balls[j];if(a.p||b.p)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),m=a.r+b.r;if(d>0&&d<m){let nx=dx/d,ny=dy/d,o=m-d;a.x-=nx*o/2;a.y-=ny*o/2;b.x+=nx*o/2;b.y+=ny*o/2;let rel=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(rel<0){a.vx-=rel*nx;a.vy-=rel*ny;b.vx+=rel*nx;b.vy+=rel*ny}}}balls.forEach(b=>{if(b.p)return;for(let p of pockets)if(Math.hypot(b.x-p[0],b.y-p[1])<27){b.p=true;b.vx=b.vy=0;tone(700,.08);if(b.q)setTimeout(()=>{b.p=false;b.x=240;b.y=H/2},400);else{turn==='player'?ps++:as++;ui()}break}});if(moving&&!mv){moving=false;if(ps>=4||as>=4){finish();return}turn=turn==='player'?'ai':'player';ui();if(turn==='ai')setTimeout(ai,600);else $('message').textContent='دورك.'}}
function finish(){active=false;if(ps>as){balance+=bet*2;wins++;streak++;best=Math.max(best,streak);xp+=diff==='pro'?120:diff==='medium'?70:40;$('message').textContent=`فزت وحصلت على ${bet*2} عملة افتراضية.`}else{losses++;streak=0;$('message').textContent='خسرت الجولة.'}save();ui()}
function ai(){let q=balls.find(b=>b.q&&!b.p),ts=balls.filter(b=>!b.q&&!b.p);if(!q||!ts.length)return;let t=ts.reduce((a,b)=>Math.hypot(b.x-q.x,b.y-q.y)<Math.hypot(a.x-q.x,a.y-q.y)?b:a),err=diff==='easy'?.34:diff==='medium'?.16:.06,ang=Math.atan2(t.y-q.y,t.x-q.x)+(Math.random()-.5)*err,p=(diff==='pro'?13:diff==='medium'?12:10)+Math.random()*4;q.vx=Math.cos(ang)*p;q.vy=Math.sin(ang)*p;moving=true;$('message').textContent='النظام يلعب...'}
function pos(e){let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
c.onpointerdown=e=>{if(!active||turn!=='player'||moving)return;let q=balls.find(b=>b.q&&!b.p),p=pos(e);if(q&&Math.hypot(p.x-q.x,p.y-q.y)<65){drag=true;start={x:q.x,y:q.y};now=p;c.setPointerCapture(e.pointerId)}}
c.onpointermove=e=>{if(drag)now=pos(e)}
c.onpointerup=e=>{if(!drag)return;drag=false;let q=balls.find(b=>b.q&&!b.p),p=pos(e),dx=start.x-p.x,dy=start.y-p.y,l=Math.hypot(dx,dy);if(l<12)return;let pw=Math.min(18,l/11);q.vx=dx/l*pw;q.vy=dy/l*pw;moving=true;tone(420);$('message').textContent='الكرات تتحرك...'}
function loop(){physics();draw();requestAnimationFrame(loop)}rack();ui();loop();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));